### ISSUE TITLE
Products Endpoints + Gzip Compression

### ISSUE THREAD

**Issue by leobz** [leobz/products_api#2]
Los endpoints deben permitir la creacion (con creación asíncrona) y la consulta de productos

## Endpoints

```
POST /products
GET   /products
```

## Tasks
- [x] TODO: async (implement Sidekiq as next step)
- [x] Implement GZIP compression if is required
- [x] Implement in memory Repository (implement Sequel as next step)
- [x] Tests

## Related info
- https://github.com/rack/rack/blob/main/lib/rack/deflater.rb

**Comment by leobz** [comment]
Closed by https://github.com/leobz/products_api/pull/9
