### ISSUE TITLE
Authentication Endpoint

### ISSUE THREAD

**Issue by leobz** [leobz/products_api#3]
Implementar endpoints de autenticación

## Endpoints

```
POST /login
Body: {username: "some_username", password: "some_password"}
```

## Tasks
- [x] Implement password hashing and password validation.
- [x] Implement JWT sessions
- [x] Securize products endpoints requiring authentication
- [x] Tests

## Related info:
- https://mmusah1.medium.com/user-authentication-in-sinatra-5ab8e1a3d6b3
- https://github.com/nickdufresne/jwt-sinatra-example 
- https://auth0.com/blog/ruby-authentication-secure-rack-apps-with-jwt/
- https://github.com/bcrypt-ruby/bcrypt-ruby
