### ISSUE TITLE
Implement OpenApi and AUTHORS endpoint

### ISSUE THREAD

**Issue by leobz** [leobz/products_api#7]
# Tasks
- [x] Generate OpenApi file
- [ ] Create Postman Collection
- [x] Generate AUTHORS file
- [x] Serve them with endpoints
- [x] Apply Cache-control with 24 hours of max-age only in AUTHORS

# Related Info
- Rack::Static:
  - https://www.rubydoc.info/gems/rack/Rack/Static
- https://github.com/rack/rack-cache
- https://www.postman.com/postman/postman-open-technologies-convert-postman-collections-into-openapi/overview
- https://joolfe.github.io/postman-to-openapi/
